# Generated by Django 3.2.6 on 2024-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('grup', models.CharField(max_length=100)),
                ('jawaban_soal_1', models.CharField(max_length=7)),
                ('jawaban_soal_2', models.CharField(max_length=7)),
                ('jawaban_soal_3', models.CharField(max_length=7)),
                ('jawaban_soal_4', models.CharField(max_length=7)),
                ('jawaban_soal_5', models.CharField(max_length=7)),
                ('skor', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
