# Generated by Django 3.2.6 on 2024-04-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kelas'),
        ),
    ]
