# Generated by Django 3.2.6 on 2024-04-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240421_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jawaban1', models.CharField(max_length=100)),
                ('skor1', models.IntegerField()),
                ('jawaban2', models.CharField(max_length=100)),
                ('skor2', models.IntegerField()),
                ('jawaban3', models.CharField(max_length=100)),
                ('skor3', models.IntegerField()),
                ('jawaban4', models.CharField(max_length=100)),
                ('skor4', models.IntegerField()),
                ('jawaban5', models.CharField(max_length=100)),
                ('skor5', models.IntegerField()),
                ('jawaban6', models.CharField(max_length=100)),
                ('skor6', models.IntegerField()),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kelas')),
            ],
        ),
    ]
