# Generated by Django 3.2.6 on 2024-05-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_evaluasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluasi',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jawaban1', models.TextField()),
                ('skor1', models.IntegerField(default=0)),
                ('jawaban2', models.TextField()),
                ('skor2', models.IntegerField(default=0)),
                ('jawaban3', models.TextField()),
                ('skor3', models.IntegerField(default=0)),
                ('jawaban4', models.TextField()),
                ('skor4', models.IntegerField(default=0)),
                ('jawaban5', models.TextField()),
                ('skor5', models.IntegerField(default=0)),
                ('jawaban6', models.TextField()),
                ('skor6', models.IntegerField(default=0)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kelas')),
            ],
        ),
    ]
